### ISSUE TITLE
Подготовка изображений по теме

### ISSUE THREAD

**Issue by itSveta** [itSveta/LR5#14]
- количество изображений: 5

**Comment by DashaPavlova** [comment]
https://github.com/itSveta/LR5/blob/master/%D0%BE%D1%82%D1%80%D0%B8%D1%86%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5%20%D1%87%D0%B8%D1%81%D0%BB%D0%B0.zip
