### ISSUE TITLE
Подготовка текстового материала

### ISSUE THREAD

**Issue by itSveta** [itSveta/LR5#4]
- подготовить теоретическую часть

**Comment by DashaPavlova** [comment]
https://github.com/itSveta/LR5/blob/master/%D0%98%D1%81%D1%82%D0%BE%D1%80%D0%B8%D1%8F%20%D0%B2%D0%BE%D0%B7%D0%BD%D0%B8%D0%BA%D0%BD%D0%BE%D0%B2%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%BE%D1%82%D1%80%D0%B8%D1%86%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D1%85%20%D1%87%D0%B8%D1%81%D0%B5%D0%BB.docx
